version: "2"
plugins:
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
checks:
  method-lines:
    config:
      threshold: 40 # It must fit into Vim screen
  method-complexity:
    config:
      threshold: 15 # We are Russian hackers!
